// AUTO-GENERATED by scripts staging (do not edit by hand).
// Curated #play14 event media — credits sourced from the media corpus manifest.
export type Orientation = "landscape" | "portrait" | "square"
export type MediaItem = { src: string; loc: string; year: string; orientation: Orientation }
export type ClipItem = MediaItem & { value: string }

export const punchins = {
  p1: {
    src: "media/photos/london-2025_2.jpg",
    loc: "London",
    year: "2025",
    orientation: "landscape",
  },
  p2: {
    src: "media/photos/amsterdam-2019_2.jpg",
    loc: "Amsterdam",
    year: "2019",
    orientation: "landscape",
  },
  p3: {
    src: "media/photos/bologna-2019_3.jpg",
    loc: "Bologna",
    year: "2019",
    orientation: "landscape",
  },
  p4: {
    src: "media/photos/porto-2018_0.jpg",
    loc: "Porto",
    year: "2018",
    orientation: "landscape",
  },
  p5: {
    src: "media/photos/hamburg-2019_18.jpg",
    loc: "Hamburg",
    year: "2019",
    orientation: "landscape",
  },
  mkt_board: {
    src: "media/photos/london-2018_6.jpg",
    loc: "London",
    year: "2018",
    orientation: "landscape",
  },
  mkt_write: {
    src: "media/photos/berlin-2026_1.jpg",
    loc: "Berlin",
    year: "2026",
    orientation: "landscape",
  },
  mkt_pitch: {
    src: "media/photos/sydney-2019_17.jpg",
    loc: "Sydney",
    year: "2019",
    orientation: "landscape",
  },
  mkt_tips: {
    src: "media/photos/kuala-lumpur-2023_19.jpg",
    loc: "Kuala Lumpur",
    year: "2023",
    orientation: "landscape",
  },
} satisfies Record<string, MediaItem>

export const boardClip: MediaItem = {
  src: "media/clips/amsterdam-2018_26.mp4",
  loc: "Amsterdam",
  year: "2018",
  orientation: "landscape",
}

export const montageByValue: Record<string, MediaItem[]> = {
  openness: [
    {
      src: "media/photos/amsterdam-2018_5.jpg",
      loc: "Amsterdam",
      year: "2018",
      orientation: "landscape",
    },
    {
      src: "media/photos/luxembourg-2024_13.jpg",
      loc: "Luxembourg",
      year: "2024",
      orientation: "landscape",
    },
    { src: "media/photos/basel-2018_16.jpg", loc: "Basel", year: "2018", orientation: "landscape" },
    {
      src: "media/photos/hamburg-2019_25.jpg",
      loc: "Hamburg",
      year: "2019",
      orientation: "landscape",
    },
  ],
  inclusion: [
    {
      src: "media/photos/bangalore-2026_16.jpg",
      loc: "Bangalore",
      year: "2026",
      orientation: "landscape",
    },
    {
      src: "media/photos/manila-2023_18.jpg",
      loc: "Manila",
      year: "2023",
      orientation: "landscape",
    },
    {
      src: "media/photos/luxembourg-2022_24.jpg",
      loc: "Luxembourg",
      year: "2022",
      orientation: "landscape",
    },
    {
      src: "media/photos/mexico-2019_0.jpg",
      loc: "Mexico",
      year: "2019",
      orientation: "landscape",
    },
  ],
  connection: [
    {
      src: "media/photos/berlin-2017_13.jpg",
      loc: "Berlin",
      year: "2017",
      orientation: "landscape",
    },
    {
      src: "media/photos/amsterdam-2019_21.jpg",
      loc: "Amsterdam",
      year: "2019",
      orientation: "landscape",
    },
    { src: "media/photos/porto-2018_8.jpg", loc: "Porto", year: "2018", orientation: "landscape" },
    {
      src: "media/photos/barcelona-2017_0.jpg",
      loc: "Barcelona",
      year: "2017",
      orientation: "landscape",
    },
  ],
  curiosity: [
    {
      src: "media/photos/luxembourg-2022_9.jpg",
      loc: "Luxembourg",
      year: "2022",
      orientation: "landscape",
    },
    {
      src: "media/photos/kuala-lumpur-2023_11.jpg",
      loc: "Kuala Lumpur",
      year: "2023",
      orientation: "landscape",
    },
    {
      src: "media/photos/berlin-2017_9.jpg",
      loc: "Berlin",
      year: "2017",
      orientation: "landscape",
    },
    {
      src: "media/photos/timisoara-2017_19.jpg",
      loc: "Timisoara",
      year: "2017",
      orientation: "landscape",
    },
  ],
  sharing: [
    {
      src: "media/photos/luxembourg-2019_20.jpg",
      loc: "Luxembourg",
      year: "2019",
      orientation: "landscape",
    },
    {
      src: "media/photos/hamburg-2018_13.jpg",
      loc: "Hamburg",
      year: "2018",
      orientation: "landscape",
    },
    {
      src: "media/photos/madrid-2019_17.jpg",
      loc: "Madrid",
      year: "2019",
      orientation: "landscape",
    },
    {
      src: "media/photos/berlin-2019_10.jpg",
      loc: "Berlin",
      year: "2019",
      orientation: "landscape",
    },
  ],
  courage: [
    {
      src: "media/photos/barcelona-2018_3.jpg",
      loc: "Barcelona",
      year: "2018",
      orientation: "landscape",
    },
    {
      src: "media/photos/timisoara-2018_22.jpg",
      loc: "Timisoara",
      year: "2018",
      orientation: "landscape",
    },
    {
      src: "media/photos/luxembourg-2015_16.jpg",
      loc: "Luxembourg",
      year: "2015",
      orientation: "landscape",
    },
    {
      src: "media/photos/sydney-2019_13.jpg",
      loc: "Sydney",
      year: "2019",
      orientation: "landscape",
    },
  ],
}

export const montageClips: ClipItem[] = [
  {
    src: "media/clips/amsterdam-2018_26.mp4",
    loc: "Amsterdam",
    year: "2018",
    orientation: "landscape",
    value: "sharing",
  },
  {
    src: "media/clips/iasi-2022_110.mp4",
    loc: "Iasi",
    year: "2022",
    orientation: "landscape",
    value: "connection",
  },
  {
    src: "media/clips/madrid-2019_18.mp4",
    loc: "Madrid",
    year: "2019",
    orientation: "landscape",
    value: "inclusion",
  },
  {
    src: "media/clips/porto-2018_62.mp4",
    loc: "Porto",
    year: "2018",
    orientation: "landscape",
    value: "courage",
  },
  {
    src: "media/clips/luxembourg-2018_172.mp4",
    loc: "Luxembourg",
    year: "2018",
    orientation: "landscape",
    value: "openness",
  },
  {
    src: "media/clips/madrid-2017_22.mp4",
    loc: "Madrid",
    year: "2017",
    orientation: "landscape",
    value: "courage",
  },
]

export const valueOrder = [
  "openness",
  "inclusion",
  "connection",
  "curiosity",
  "sharing",
  "courage",
] as const
